'use client'
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { useState } from 'react';
import './globals.css';
import { HiMenu, HiOutlineX } from 'react-icons/hi';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [show, setShow] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-5 bg-white shadow md:flex md:items-center md:justify-between md:px-20 px-5">
          <div className="flex justify-between items-center">
            <Image
              src="/logo.png"
              alt="Logo"
              width={200}
              height={50}
            />
            <button
              type="button"
              onClick={() => setShow(!show)}
              className="inline-flex items-center border-[1px] p-3 w-15 h-15 justify-center text-sm text-gray-500 rounded-full border-black md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
            >
              <span className="sr-only">Open main menu</span>
              {show ? <HiOutlineX size={25} /> : <HiMenu size={25} />}
            </button>
          </div>

          <ul
            className={`md:flex md:items-center md:z-auto md:static absolute bg-white w-full left-0 md:w-auto md:py-0 py-4 md:pl-0 md:opacity-100 opacity-0 transition-all ease-in duration-500 ${
              show ? 'top-20 opacity-100 z-[1] h-full' : 'top-[-400px] z-[-1]'
            }`}
          >
            <li className="px-4 py-6 pl-7 md:py-0 bg-neutral-950 md:bg-transparent">
              <Link
                href="/"
                className="text-base hover:text-cyan-500 duration-500 text-white rounded md:bg-transparent md:text-neutral-950 dark:text-white md:dark:text-neutral-950"
              >
                PAKAR 1
              </Link>
            </li>
            <li className="px-4 py-6 pl-7 md:py-0">
              <Link
                href="/survey-2"
                className="text-base hover:text-cyan-500 duration-500 text-neutral-600 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-neutral-800 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
              >
                PAKAR 2
              </Link>
            </li>
            {/* <li className="px-4 py-6 pl-7 md:py-0">
              <a
                href="#"
                className="text-base hover:text-cyan-500 duration-500 text-neutral-600 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-neutral-800 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
              >
                ABOUT
              </a>
            </li>
            <li className="px-4 py-6 pl-7 md:py-0">
              <a
                href="#"
                className="text-base hover:text-cyan-500 duration-500 text-neutral-600 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-neutral-800 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
              >
                CONTACT
              </a>
            </li>
            <li className="px-4 py-6 pl-7 md:py-0">
              <a
                href="#"
                className="text-base hover:text-cyan-500 duration-500 text-neutral-600 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-neutral-800 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
              >
                BLOG
              </a>
            </li> */}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
